/// <reference_path="./definitions/jquery.d.ts" />
/// <reference_path="./definitions/i18next.d.ts" />

export module CyEnumerations {
    export enum AlarmActiveState {
        AS_Cleared = 0,
        AS_Set = 1,
    }

    export enum AlarmSeverity {
        Indeterminate = 0,
        NonAlarmed = 1,
        Free_Choice = 2,
        Warning = 3,
        Minor = 4,
        Major = 5,
        Critical = 6,
        Cleared = 7
    }

    export enum AlarmServiceAffecting {
        SA_UNKNOWN = 0,
        SA_SERVICE_AFFECTING = 1,
        SA_NON_SERVICE_AFFECTING = 2
    }

    export enum AlarmCategory {
        Unknown = 0,
        BITS = 1,
        COM = 7,
        ENV = 8,
        EQPT = 9,
        SLK = 10,
        STM16RS = 11,
        OC48S = 12,
        STM64RS = 13,
        OC192S = 14,
        STM1RS = 15,
        OC3S = 16,
        STM4RS = 17,
        OC12S = 18,
        STM16MS = 21,
        OC48L = 22,
        STM64MS = 23,
        OC192L = 24,
        STM1MS = 25,
        OC3L = 26,
        STM4MS = 27,
        OC12L = 28,
        OTU1 = 31,
        OTU2 = 32,
        ODU1 = 41,
        ODU2 = 42,
        VC44 = 45,
        VC416 = 46,
        STS1 = 51,
        STS3c = 52,
        STS12c = 53,
        STS48c = 54,
        STS192c = 55,
        VC3 = 56,
        VC4 = 57,
        VC44c = 58,
        VC416c = 59,
        VC464c = 60,
        FAC = 61,
        OCC = 62,
        OCH = 63,
        ETH = 64,
        EthFP = 65,
        EthFPP = 66,
        GTP = 67,
        APS = 68,
        LINK = 69,
        GFP = 70,
        MEP = 71,
        VCG = 72,
        PG = 81,
        DBCHG = 252,
        SECU = 253,
        SYNC = 254,
        ALL = 255,
    }

    export enum NoYes {
        No,
        Yes
    }

    export enum ProbableCause {
        NA = 0,
        UNEQUIPPED = 1,
        EQPT_RESTART = 2,
        EQPT_FAIL = 3,
        EQPT_DGRADE = 4,
        EQPT_MISMTCH = 5,
        EQPT_UNEXPECTED = 6,
        EQPT_WARNING = 7,
        NOT_CONFIG = 8,
        AUTO_UPGRADE = 11,
        BAT_FAIL = 31,
        BAT_DGRADE = 32,
        PRE_AMP = 50,
        TP_LOS = 51,
        TP_LOC = 52,
        TP_LOF = 53,
        TP_AIS = 54,
        TP_LOM = 55,
        TP_SF = 56,
        TP_BDI = 57,
        TP_FDI = 58,
        TP_PMI = 59,
        TP_SD = 60,
        TP_RDI = 61,
        TP_TIM = 62,
        TP_IAE = 63,
        TP_BIAE = 64,
        TP_OCI = 65,
        TP_LCK = 66,
        TP_LOFLOM = 67,
        TP_SSF = 68,
        TP_OORANGE_ALM = 69,
        TP_OORANGE_WRN = 70,
        TP_FACLPBK = 71,
        TP_HIGH_LOSS = 72,
        TP_LOW_LOSS = 73,
        TP_FIBER = 74,
        TP_PLM = 75,
        TP_LTC = 76,
        TP_MSIM = 77,
        PROT_FAIL = 78,
        CCM = 79,
        TP_LFD = 80,
        TP_LINK = 81,
        TP_GFP = 82,
        TP_TPT = 83,
        GTP = 84,
        TP_SQM = 85,
        TP_LOA = 86,
        TP_LTI = 87,
        LTM = 88,
        APS = 89,
        TP_LOP = 90,
        TP_UNEQ = 91,
        CSF = 92,
        EXMISM = 93,
        UPM = 94,
        PROT_CMD = 95,
        FAREND_CMD = 96,
        PROTOCOL_ERR = 97,
        LOOPBACK = 98,
        LMM = 99,
        DMM = 100,
        COMM_FAIL = 101,
        COMM_DGRADE = 102,
        PACKET_LPBK = 103,
        XCSPKTSLOSS = 104,
        XCSPKTSERR = 105,
        SRCADDRMIS = 106,
        ARP = 107,
        TSA = 108,
        ERP_PORT = 109,
        TP_LOOMFI = 110,
        SYNC_FAIL = 201,
        SYNC_DGRADE = 202,
        HOLDOVER = 203,
        XCSHOLDOVER = 204,
        SYNC_EXCMD_ACTIVE = 205,
        ENV_ALM = 301,
        ENV_WRN = 302,
        INCMPLD = 401,
        ADMIN = 402
    }
    export enum ProbableCauseQualifier {
        NA = 0,
        COMM1 = 1,
        COMM2 = 2,
        UNASSIGNED = 3,
        HI_RXPWR = 4,
        LOW_RXPWR = 5,
        HI_TXPWR = 6,
        LOW_TXPWR = 7,
        HI_VOLTAGE = 8,
        LOW_VOLTAGE = 9,
        HI_CURRENT = 10,
        LOW_CURRENT = 11,
        HI_TEMP_RISE = 12,
        MEM_ACCESS = 13,
        PWR_A_OVER_VLTG = 14,
        PWR_A_UNDER_VLTG = 15,
        EID_INVALID = 16,
        MEM_FULL = 17,
        MEM_LOW = 18,
        WARM_UP = 19,
        MID_STAGE = 20,
        FUSE1_FAIL = 21,
        FUSE2_FAIL = 22,
        FUSE3_FAIL = 23,
        FUSE4_FAIL = 24,
        PWR_FEED1_LOSS = 25,
        PWR_FEED2_LOSS = 26,
        PWR_FEED3_LOSS = 27,
        PWR_FEED4_LOSS = 28,
        PWR_A = 29,
        PWR_B = 30,
        OCH = 31,
        OVERHEAD = 32,
        PAYLOAD = 33,
        PROV_MISM = 34,
        NO_RESP = 35,
        FAR_END = 36,
        HI_RXPWR_OH = 37,
        LOW_RXPWR_OH = 38,
        HI_TXPWR_OH = 39,
        LOW_TXPWR_OH = 40,
        TX_FREQ = 41,
        RX_FREQ = 42,
        ALL_PWR_FEEDS = 43,
        UNIT_A = 44,
        UNIT_B = 45,
        TX = 46,
        RX = 47,
        XOVER = 48,
        TX_PAYLOAD = 49,
        TEC = 50,
        XCON = 51,
        ERROR = 52,
        RMEP = 53,
        MAC_STAT = 54,
        RDI = 55,
        UNIT_C = 56,
        UNIT_D = 57,
        I2C_ERR = 58,
        RT_DIAG_NOTSUPP = 59,
        UNCERTIFIED = 60,
        DUP_IPADDR = 61,
        DUP_NODENAME = 62,
        SNTP_HOST = 63,
        SSF = 64,
        DYING_GASP = 65,
        CRITICAL = 66,
        PWR_FEED_LOSS = 67,
        MAX_TCA = 68,
        PACKET = 69,
        MISMERGE = 70,
        UNEXMEL = 71,
        UNEXMEP = 72,
        UNEXPERIOD = 73,
        LACP = 74,
        CFG_NOTSUPP = 75,
        LOW_RXSPANLOSS = 81,
        HI_RXSPANLOSS = 82,
        DISK_LOW = 83,
        CPU_HI = 84,
        MFGMODE = 85,
        IPC = 86,
        FAREND_SF_P = 90,
        PROTOCOL = 91,
        NODE_ID_MISM = 92,
        FAREND_SF_W = 93,
        APS_BYTE_FAIL = 94,
        DFLT_KBYTES = 95,
        APS_MODE_MISM = 96,
        LOCKOUT = 97,
        MANUAL = 98,
        FORCED = 99,
        ESMC = 100,
        OSC_PRTCL = 101,
        DCC_FAIL = 102,
        GCC0_FAIL = 103,
        GCC12_FAIL = 104,
        APS_CH_MISM = 105,
        APSINCMPLD = 106,
        CCM = 107,
        PATH = 108,
        BLOCKED = 109,
        DSBLD = 110,
        FAIL = 111,
        CSF = 112,
        LFD = 113,
        EXMISM = 114,
        SSM = 115,
        IP = 116,
        UPM = 117,
        MAINT = 118,
        SW_MISM = 201,
        SW_BAD = 202,
        DB_MISM = 203,
        DB_BAD = 204,
        SW_UPGRADE_FAIL = 205,
        SW_UPGRADE_DSBLD = 206,
        HI_TEMP = 301,
        LOW_TEMP = 302,
        HI_TEMP_IN = 303,
        LOW_TEMP_IN = 304,
        HI_TEMP_OUT = 305,
        LOW_TEMP_OUT = 306,
        FAN_FILTER_DIRTY = 380,
        DEVICE = 381,
        PWR_B_OVER_VLTG = 382,
        PWR_B_UNDER_VLTG = 383,
        DEVICE_GPIO = 384,
        PWR_FEED_OVER_VLTG = 385,
        PWR_FEED_UNDER_VLTG = 386,
        COMPRESSOR_FAIL = 401,
        AIR_CONDITIONING_FAIL = 402,
        AIR_DRYER_FAIL = 403,
        BATTERY_DISCHARGE = 404,
        BATTERY_FAIL = 405,
        COOL_FAN_FAIL = 406,
        ENGINE_FAIL = 407,
        ENGINE_OPERATING = 408,
        EXPLOSIVE_GAS = 409,
        FIRE_DETECTOR_FAIL = 410,
        FIRE = 411,
        FLOOD = 412,
        FUSE_FAIL = 413,
        GENERATOR_FAIL = 414,
        HI_AIRFLOW = 415,
        HI_HUMIDITY = 416,
        HI_WATER = 417,
        INTRUSION = 418,
        LOW_BATTERY_VOLTAGE = 419,
        LOW_FUEL = 420,
        LOW_HUMIDITY = 421,
        LOW_CABLE_PRESS = 422,
        LOW_WATER = 423,
        USER_DEFINED_ALM1 = 424,
        OPEN_DOOR = 425,
        COMM_POWER_FAIL = 426,
        PUMP_FAIL = 427,
        POWER_SUPPLY_FAIL = 428,
        RECTIFIER_FAIL = 429,
        RECTIFIER_HI_VOLTAGE = 430,
        RECTIFIER_LOW_VOLTAGE = 431,
        SMOKE = 432,
        TOXIC_GAS = 433,
        VENTILATION_FAIL = 434,
        USER_DEFINED_ALM2 = 435,
        USER_DEFINED_ALM3 = 436,
        USER_DEFINED_ALM4 = 437,
        USER_DEFINED_ALM5 = 438,
        REMOTE_ACO = 439,
        HEAT_EXCHANGER_FAIL = 440,
        RECTIFIER_FAIL_MJR = 441
    }
    export enum Type {
        Unknown = 0,
        UnEquipped = 1,
        UnAvailable = 2,
        CYAN_MS = 3,
        CYAN_Network = 4,
        CYAN_TopologicalLine = 5,
        CYAN_TopologicalLink = 6,
        CYAN_Z77 = 7,
        CYAN_Shelf16Slot = 8,
        CYAN_Shelf16 = 9,
        CYAN_Shelf8 = 10,
        CYAN_XFPSlot = 11,
        CYAN_SFPSlot = 12,
        CYAN_AMCSlot = 13,
        CYAN_LAMPCoreEqpt = 14,
        CYAN_LAMPShelf = 15,
        CYAN_LAMP = 16,
        CYAN_ShelfSlot = 17,
        CYAN_Z33 = 18,
        CYAN_LGX3Shelf = 19,
        CYAN_OFX4 = 20,
        CYAN_PEMSlot = 21,
        CYAN_BTMSlot = 22,
        CYAN_RTMSlot = 23,
        CYAN_OpticalFabricSlot = 24,
        CYAN_PacketFabricSlot = 25,
        CYAN_AWG40 = 26,
        CYAN_AWG40Shelf = 27,
        CYAN_Shelf16v2 = 28,
        CYAN_Shelf4 = 29,
        CYAN_CemSlot = 30,
        CYAN_BossSlot = 31,
        CYAN_FIMSlot = 32,
        CYAN_FanSlot = 33,
        CYAN_OpPanelSlot = 34,
        CYAN_Z77FanSlot = 35,
        CYAN_Z22 = 36,
        CYAN_SFPpSlot = 37,
        CYAN_CFPSlot = 38,
        CYAN_LAD2G = 96,
        CYAN_Z22Fan = 97,
        CYAN_Z77Fan = 98,
        CYAN_LAD2P = 99,
        CYAN_Z33Fan = 100,
        CYAN_BOSS = 101,
        CYAN_LSW = 102,
        CYAN_LMX4 = 103,
        CYAN_LXC409 = 104,
        CYAN_LAD4E = 105,
        CYAN_Fan = 106,
        CYAN_OperationPanel = 107,
        CYAN_CEM = 108,
        CYAN_PSW2 = 109,
        CYAN_PMX212 = 110,
        CYAN_MiniFan = 111,
        CYAN_LAD4 = 112,
        CYAN_LAD4A = 113,
        CYAN_MSE1482 = 114,
        CYAN_PSX280 = 115,
        CYAN_PSW20 = 116,
        CYAN_LAD2P_LGX = 117,
        CYAN_PME412 = 118,
        CYAN_SMX28 = 119,
        CYAN_SMX416 = 120,
        CYAN_LME4 = 121,
        CYAN_LAD8 = 122,
        CYAN_LAD8A = 123,
        CYAN_LAD8E = 124,
        CYAN_PSW6 = 125,
        CYAN_DTM8G = 126,
        CYAN_LAD2G_LGX = 127,
        CYAN_DTM8 = 128,
        CYAN_SFT8 = 129,
        CYAN_LAC8 = 130,
        CYAN_LedPanel = 131,
        CYAN_WSS402 = 132,
        CYAN_WSS404 = 133,
        CYAN_PME216 = 135,
        CYAN_WMX = 136,
        CYAN_CEMi = 137,
        CYAN_LAD8i = 138,
        CYAN_LAD40 = 139,
        CYAN_LAD40E = 140,
        CYAN_OSW10G8 = 142,
        CYAN_XC2800 = 143,
        CYAN_TSW10 = 144,
        CYAN_PME216T = 145,
        CYAN_BOSS2 = 146,
        CYAN_DTM4 = 147,
        CYAN_LAD8X = 148,
        CYAN_SFT10G16 = 149,
        CYAN_FLX216 = 150,
        CYAN_DTM100G = 151,
        CYAN_PSW10 = 152,
        CYAN_PSW618 = 153,
        CYAN_XFPXcvr = 201,
        CYAN_CFPXcvr = 202,
        CYAN_SFPXcvr = 204,
        CYAN_AMC = 207,
        CYAN_PEM2 = 299,
        CYAN_LAMPBTM = 300,
        CYAN_BTM = 301,
        CYAN_OF9 = 302,
        CYAN_PXC280 = 303,
        CYAN_PEM = 304,
        CYAN_R_1G8SFP = 305,
        CYAN_RTM2X = 306,
        CYAN_R_1G8 = 307,
        CYAN_RCM = 308,
        CYAN_MidStagePTP = 309,
        CYAN_EQPT_CLOCK_TTP = 310,
        CYAN_STM1MS_TTP = 311,
        CYAN_STM4MS_TTP = 312,
        CYAN_STM16MS_TTP = 313,
        CYAN_STM64MS_TTP = 314,
        CYAN_SAUG1_TTP = 315,
        CYAN_AUG1_TTP = 316,
        CYAN_AUG4_TTP = 317,
        CYAN_AUG16_TTP = 318,
        CYAN_AUG64_TTP = 319,
        CYAN_SAUG4_TTP = 320,
        CYAN_STM1RS_TTP = 321,
        CYAN_STM4RS_TTP = 322,
        CYAN_STM16RS_TTP = 323,
        CYAN_STM64RS_TTP = 324,
        CYAN_MuxAddDropFiberPTP = 325,
        CYAN_OcgPTP = 326,
        CYAN_TxExtSD_TTP = 327,
        CYAN_TxSD_TTP = 328,
        CYAN_RxSD_TTP = 329,
        CYAN_AddDropCwdmFiberPTP = 330,
        CYAN_LineTimingTTP = 331,
        CYAN_3RFiberPTP = 332,
        CYAN_10GAFiberPTP = 333,
        CYAN_LADOSC_TTP = 334,
        CYAN_LADAOMS_TTP = 335,
        CYAN_LADOMS_TTP = 336,
        CYAN_AddDropFiberPTP = 337,
        CYAN_S1FiberPTP = 338,
        CYAN_S4FiberPTP = 339,
        CYAN_S16FiberPTP = 340,
        CYAN_S16MRFiberPTP = 341,
        CYAN_S64FiberPTP = 342,
        CYAN_OTU2FiberPTP = 343,
        CYAN_LADEOTM_PTP = 344,
        CYAN_SdhLinkFTP = 345,
        CYAN_ExtCC2MHzRxTTP = 346,
        CYAN_ExtCC2MhzPTP = 347,
        CYAN_PfLinkTTP = 348,
        CYAN_LinkFTP = 349,
        CYAN_10GEMFiberPTP = 350,
        CYAN_ElectricalCTP = 351,
        CYAN_OTM_PTP = 352,
        CYAN_FiberPTP = 353,
        CYAN_FiberTTP = 354,
        CYAN_10GFiberPTP = 355,
        CYAN_10GEFiberPTP = 356,
        CYAN_DerivedTimingReference = 357,
        CYAN_TimingRefFTP = 358,
        CYAN_TSS = 359,
        CYAN_ExtTimingReference = 360,
        CYAN_TimingReference = 361,
        CYAN_ExtTimingPTP = 362,
        CYAN_ExtTimingTxTTP = 363,
        CYAN_ExtTimingRxTTP = 364,
        CYAN_OC48_TTP = 365,
        CYAN_STM16_TTP = 366,
        CYAN_OC192_TTP = 367,
        CYAN_STM64_TTP = 368,
        ITU_OTU1GCC0TP = 369,
        ITU_OTU2GCC0TP = 370,
        ITU_ODU1GCC12TP = 371,
        ITU_ODU2GCC12TP = 372,
        CYAN_ODU1Nim = 373,
        CYAN_ODU2Nim = 374,
        CYAN_ODU1CTP = 375,
        CYAN_ODU2CTP = 376,
        CYAN_ODU1TCM_TTP = 377,
        CYAN_ODU2TCM_TTP = 378,
        CYAN_ClientFTP = 379,
        CYAN_ODU1TTP = 380,
        CYAN_ODU2TTP = 381,
        CYAN_OTUkCTP = 382,
        CYAN_OTU1TTP = 383,
        CYAN_OTU2TTP = 384,
        CYAN_FIBEROTU2TTP = 385,
        CYAN_OcgTTP = 386,
        CYAN_OccNimCTP = 387,
        CYAN_OccTTP = 388,
        CYAN_OchTTP = 389,
        CYAN_OscTTP = 390,
        CYAN_OMS_TTP = 391,
        CYAN_OTS_TTP = 392,
        CYAN_LAG = 393,
        CYAN_LAMPOTM_PTP = 394,
        CYAN_LADOTM_PTP = 395,
        CYAN_LADAOTM_PTP = 396,
        CYAN_LADOTS_TTP = 397,
        CYAN_TETY_TTP = 398,
        CYAN_MAU_TTP = 399,
        CYAN_MAUT_TTP = 400,
        CYAN_GFP_TTP = 401,
        CYAN_ETTY_TTP = 402,
        CYAN_ETY31_PTP = 403,
        CYAN_ETY32_PTP = 404,
        CYAN_GigEPTP = 405,
        CYAN_EthernetTTP = 406,
        CYAN_ETY_TTP = 407,
        CYAN_DcnPTP = 408,
        PBB_ESP_TESI = 409,
        PBB_FlowPointPool = 410,
        CYAN_EthFlowPointPool = 411,
        CYAN_EthUNI = 412,
        CYAN_EthNNI = 413,
        CYAN_OccCTP = 414,
        CYAN_EthLagFPP = 415,
        CYAN_GFECOTU2TTP = 416,
        CYAN_TETY10G_TTP = 417,
        CYAN_ETTY10G_TTP = 418,
        CYAN_LADEOTS_TTP = 419,
        CYAN_LADEOMS_TTP = 420,
        CYAN_EthFlowPoint = 421,
        PBB_FlowPoint = 422,
        CYAN_EOS_API = 423,
        CYAN_OTU2eTTP = 424,
        Dot1agMip = 425,
        CYAN_EthLagFlowPoint = 426,
        CYAN_ODU2eTTP = 427,
        CYAN_UFECOTU2TTP = 428,
        CYAN_10GEOFiberPTP = 429,
        CYAN_WMXOTM_PTP = 430,
        Dot3ahMep = 431,
        CYAN_EOAM_API = 432,
        CYAN_EthFlowDomain = 433,
        CYAN_EthBridge = 434,
        Dot1agMd = 435,
        Dot1agMa = 436,
        Dot1agMep = 437,
        CYAN_FTP = 438,
        CYAN_VCG = 439,
        PBB_GTP = 440,
        CYAN_EthBwProfile = 441,
        CYAN_EthCosProfile = 442,
        CYAN_EthQueueProfile = 443,
        CYAN_UserEthQueueProfile = 444,
        CYAN_UserEthBwProfile = 445,
        CYAN_EthLinkOAMProfile = 446,
        CYAN_UserEthLinkOAMProfile = 447,
        CYAN_EthKbwProfile = 448,
        CYAN_UserEthKbwProfile = 449,
        CYAN_SDHSONET_API = 450,
        CYAN_XGEWAN_TTP = 451,
        CYAN_AddDropWwdmFiberPTP = 452,
        CYAN_MultiFiberTP = 453,
        CYAN_OcgeTTP = 454,
        CYAN_SETH_TTP = 455,
        CYAN_LADOcgPTP = 456,
        CyanMd = 457,
        CYAN_ETY32B_PTP = 458,
        CYAN_GigEPTPNoPmStats = 459,
        CYAN_EthernetTTPwPmStats = 460,
        CYAN_GigEPTPNoPmStatsRoute = 461,
        CYAN_10GAOFiberPTP = 462,
        CYAN_ODU0TTP = 463,
        CYAN_ODUflexTTP = 464,
        CYAN_ODU2MuxTTP = 465,
        CYAN_ODU1MuxTTP = 466,
        CYAN_ERPP_GTP = 467,
        ERP_FlowPointPool = 468,
        ERP_FlowPoint = 469,
        CYAN_SETH_TxTTP = 470,
        CYAN_LAD40EOTM_PTP = 471,
        CYAN_3R10GMRFiberPTP = 472,
        CYAN_LAD8XOTM_PTP = 473,
        CYAN_10GEOpFiberPTP = 474,
        CYAN_NETTY10G_TTP = 475,
        CYAN_ERPv2_Profile = 476,
        CYAN_UserERPv2_Profile = 477,
        CYAN_PathPG = 478,
        CYAN_EthOAMProfile = 479,
        CYAN_UserEthOAMProfile = 480,
        EProtectionGroup_T = 481,
        CYAN_PG = 482,
        CYAN_OpticalPG = 483,
        CYAN_MSPR_PG = 484,
        CYAN_TESIEXPRESS_API = 485,
        CYAN_ERP = 486,
        CYAN_S0_CTP = 487,
        CYAN_S1_CTP = 488,
        CYAN_S4_CTP = 489,
        CYAN_S16_CTP = 490,
        CYAN_S0_TTP = 491,
        CYAN_S1_TTP = 492,
        CYAN_S4_TTP = 493,
        CYAN_S16_TTP = 494,
        CYAN_S64_TTP = 495,
        CYAN_TimingRefProfile = 496,
        CYAN_TimingRefProfileLine = 497,
        CYAN_ERP_Profile = 498,
        CYAN_UserERP_Profile = 499,
        CYAN_EthScheduleProfile = 500,
        CIM_OSPFService = 501,
        CIM_IPProtocolEndpoint = 502,
        CIM_IPInterface = 503,
        CIM_OSPFProtocolEndpoint = 504,
        CIM_OSPFInterface = 505,
        CIM_OSPFArea = 506,
        CYAN_OSPFLSDB = 507,
        CYAN_OSPFNeighbor = 508,
        CIM_DCNIP_TTP = 509,
        CIM_DCNOSPF_TTP = 510,
        CYAN_UserEthScheduleProfile = 511,
        CYAN_AFECOTU2TTP = 512,
        CYAN_MRFlxPTP = 513,
        CYAN_100GEMFiberPTP = 514,
        CYAN_TETY100G_TTP = 515,
        CYAN_OTU4TTP = 516,
        CYAN_GFECOTU4TTP = 517,
        CYAN_ODU4TTP = 518,
        CYAN_OTM04_PTP = 519,
        CYAN_OccrCTP = 520,
        CYAN_Section155M_TTP = 521,
        CYAN_Section622M_TTP = 522,
        CYAN_Section2488M_TTP = 523,
        CYAN_OcgWssPTP = 524,
        CYAN_ETY_LB_TTP = 525,
        CYAN_10GEpFiberPTP = 526,
        CYAN_CrossConnect = 601,
        CYAN_SubnetworkConnection = 602,
        CYAN_STA = 603,
        CYAN_PcapFile = 604,
        CYAN_SVC_API = 605,
        CYAN_MiniRoot = 702,
        ASAP_T = 703,
        TCAParameterProfile_T = 704,
        PMP_T = 705,
        CYAN_OpticalTCAParameterProfile = 706,
        UserTCAParameterProfile_T = 707,
        CYAN_UserOpticalTCAParamProfile = 708,
        CYAN_LAGP = 709,
        User_ASAP_T = 710,
        CYAN_BurstyDegThresholdProfile = 711,
        CYAN_SONETSDHMSProfile = 712,
        CYAN_ShelfProfile = 713,
        CYAN_EthPCP2CosPidProfile = 714,
        CYAN_SONETSDHVCProfile = 715,
        CYAN_AUGnProfile = 716,
        CYAN_InternalClockGen = 717,
        CYAN_StationClockGen = 718,
        CYAN_UserSONETSDHVCProfile = 719,
        CYAN_UserSONETSDHMSProfile = 720,
        CYAN_UserEthPCP2CosPidProfile = 721,
        CYAN_UserBurstyDegThresholdProfile = 722,
        CYAN_UserPGProfile = 723,
        CYAN_UserMSPR_Profile = 724,
        CYAN_UserLAGP = 725,
        CYAN_DSCP2CosPidProfile = 726,
        CYAN_UserDSCP2CosPidProfile = 727,
        TCAParameterProfile = 728,
        UserTCAParameterProfile = 729,
        MEP_TCAParameterProfile = 730,
        UserMEP_TCAParameterProfile = 731,
        CYAN_OchTCAParameterProfile = 732,
        CYAN_UserOchTCAParamProfile = 733,
        CYAN_User = 800,
        CYAN_Role = 801,
        CYAN_SshKeys = 802
    }
    export enum LayerRate {
        NA = 0,
        Fiber = 1,
        Electrical = 2,
        OCh = 3,
        Odu1 = 4,
        Odu2 = 5,
        Odu3 = 6,
        Ethernet = 7,
        GigEthernet = 8,
        TenGigEthernet = 9,
        GFP = 10,
        EthernetTunnel = 11,
        OcgFiber = 12,
        Odu2e = 13,
        Otu2 = 14,
        Otu2e = 15,
        Otu1e = 16,
        Odu1e = 17,
        Odu0 = 18,
        Oduflex = 19,
        Otu4 = 20,
        VC3 = 21,
        VC4 = 22,
        VC4_4c = 23,
        VC4_16c = 24,
        VC4_64c = 25,
        Odu4 = 26,
        Otu2f = 28,
        Otu1f = 29,
        STM1MS = 31,
        STM4MS = 32,
        STM16MS = 33,
        STM64MS = 34,
        Fiber100G = 40,
        MultiFiber3 = 41,
        MultiFiber10G10 = 42
    }

    export var EnumTypeStrings:{ [key:string]: any} =  {
            "alarmState": AlarmActiveState,
            "AlarmSeverityEnums": AlarmSeverity,
            "alarmCategory": AlarmCategory,
            "ServiceAffecting": AlarmServiceAffecting,
            "noYes": NoYes,
            "probableCause": ProbableCause,
            "probableCauseQualifier": ProbableCauseQualifier,
            "type": Type,
            "LayerRate": LayerRate
    };

    /**
     * Singleton which maintains the kendo mapping for the enumerations defined above.  The mappings are created lazily.
     */
    export class KendoMappings {

        private static _instance:KendoMappings = null;
        private _mappings = {};

        constructor() {

        }

        /**
         * Get instance
         * @returns {KendoMappings}
         * @constructor
         */
        public static get I():KendoMappings {
            if (KendoMappings._instance === null) {
                KendoMappings._instance = new KendoMappings();
            }
            return KendoMappings._instance;
        }

        /**
         * Get the mapping for a specific type and create it if it does not exist
         * @param type      the enum type
         * @returns {*}
         */
        public getKendoMapping(type:string) {
            if (!(type in this._mappings)) {

                if (type in EnumTypeStrings) {
                    this._mappings[type] = this._buildKendoMapping(type);
                } else {
                    return [];
                }
            }

            return this._mappings[type];
        }

        /**
         * Builds the mapping needed for Kendo.  The format is an array of objects consisting of properties (value,text)
         * Note: This is only temporary until I can build a string table for enums
         * @param type      the enum type string
         * @returns {Array}
         * @private
         */
        private _buildKendoMapping(type:string):any[] {

            var foreignKeys = [];
            var enumType = EnumTypeStrings[type];
            // typescript stores enums as an object mapped from enum_type -> value and value -> enum_type
            for (var key in enumType) {

                var text = $.t('cyms:' + type + '.' + enumType[key]);

                // if the text didn't localize properly, don't display it

                if (!text.match(/cyms/)) {
                    // if key is not a number
                    foreignKeys.push({
                        value: key,
                        text: text
                    });
                }

            }

            return foreignKeys;
        }
    }
}